- name: apiserver client scheduler certs directory
  tags: cert
  file:
    path: "{{ apiserver_client_certs_scheduler }}/{{ item }}"
    state: directory
  with_items:      
    - "{{ groups['scheduler'] }}"

- name: apiserver client scheduler key
  tags: cert
  openssl_privatekey:
    path: "{{ apiserver_client_certs_scheduler }}/{{ item }}/key.pem"
  with_items:      
    - "{{ groups['scheduler'] }}"


- name: apiserver client scheduler csr
  tags: cert
  openssl_csr:
    path: "{{ apiserver_client_certs_scheduler }}/{{ item }}/cert.csr"
    privatekey_path: "{{ apiserver_client_certs_scheduler }}/{{ item }}/key.pem"
    common_name: "system:kube-scheduler"
  with_items:      
    - "{{ groups['scheduler'] }}"

# this task will always generate new certs to cover previous certs
- name: apiserver client scheduler cert
  tags: cert
  shell: openssl x509 -req -days 365 -in {{ apiserver_client_certs_scheduler }}/{{ item }}/cert.csr -CA {{ ca_path }}/ca.pem  -CAkey {{ ca_path }}/key.pem -CAcreateserial -out {{ apiserver_client_certs_scheduler }}/{{ item }}/cert.pem
  with_items:      
    - "{{ groups['scheduler'] }}"
