- name: apiserver client controller certs directory
  tags: cert
  file:
    path: "{{ apiserver_client_certs_controller }}/{{ item }}"
    state: directory
  with_items:      
    - "{{ groups['controller'] }}"

- name: apiserver client controller key
  tags: cert
  openssl_privatekey:
    path: "{{ apiserver_client_certs_controller }}/{{ item }}/key.pem"
  with_items:      
    - "{{ groups['controller'] }}"


- name: apiserver client controller csr
  tags: cert
  openssl_csr:
    path: "{{ apiserver_client_certs_controller }}/{{ item }}/cert.csr"
    privatekey_path: "{{ apiserver_client_certs_controller }}/{{ item }}/key.pem"
    common_name: "system:kube-controller-manager"
    organization_name: "system:masters"
  with_items:      
    - "{{ groups['controller'] }}"

# this task will always generate new certs to cover previous certs
- name: apiserver client controller cert
  tags: cert
  shell: if [ -f {{ apiserver_client_certs_controller }}/{{ item }}/cert.pem ];then exit; else openssl x509 -req -days 365 -in {{ apiserver_client_certs_controller }}/{{ item }}/cert.csr -CA {{ ca_path }}/ca.pem -CAkey {{ ca_path }}/key.pem -CAcreateserial -out {{ apiserver_client_certs_controller }}/{{ item }}/cert.pem;fi 
  with_items:      
    - "{{ groups['controller'] }}"
