- name: ca key
  tags: ca
  openssl_privatekey:
    path: "{{ item }}/key.pem"
  with_items:      
    - "{{ ca_path }}"

- name: ca csr
  tags: ca
  openssl_csr:
    path: "{{ item }}/ca.csr"
    privatekey_path: "{{ item }}/key.pem"
    common_name: "selfsigned-ca"
  with_items:      
    - "{{ ca_path }}"

- name: ca cert      
  tags: ca
  openssl_certificate:
    path: "{{ item }}/ca.pem"
    privatekey_path: "{{ item }}/key.pem"
    csr_path: "{{ item }}/ca.csr"
    provider: selfsigned
  with_items:      
    - "{{ ca_path }}"
