- name: serviceAccount key
  tags: ca
  openssl_privatekey:
    path: "{{ item }}/key.pem"
  with_items:      
    - "{{ serviceAccount_path }}"

- name: serviceAccount csr
  tags: ca
  openssl_csr:
    path: "{{ item }}/ca.csr"
    privatekey_path: "{{ item }}/key.pem"
    common_name: "serviceAccount-ca"
  with_items:      
    - "{{ serviceAccount_path }}"

- name: serviceAccount cert      
  tags: ca
  openssl_certificate:
    path: "{{ item }}/ca.pem"
    privatekey_path: "{{ item }}/key.pem"
    csr_path: "{{ item }}/ca.csr"
    provider: selfsigned
  with_items:      
    - "{{ serviceAccount_path }}"
