- name: create directory
  file:
    path: "{{ kubelet_install_path }}/{{ item }}"
    state: directory
  with_items:      
    - 'bin'
    - 'cert'
    - 'data'
    - 'log'

- name: upload config
  notify: restart kuberouter
  template: 
    src: supervisord.conf.j2
    dest: "{{ kubelet_install_path }}/supervisord.conf"

- name: upload config
  notify: restart kuberouter
  template: 
    src: kubeconfig.yml.j2
    dest: "{{ kubelet_install_path }}/kubeconfig.yml"

- name: upload kubelet
  notify: restart kuberouter
  copy: 
    src: "{{ item }}"
    dest: "{{ kubelet_install_path }}/bin/"
    mode: u=rwx
  with_items:
    - "{{ build_path }}/build-kubernetes/kubernetes/_output/local/bin/linux/amd64/kubelet"

- name: upload certs ca
  notify: restart kuberouter
  copy:
    src: "{{ item }}"
    dest: "{{ kubelet_install_path }}/cert/ca/"
  with_items:
    - "{{ ca_path }}/ca.pem"

- name: upload kubelet certs 
  notify: restart kuberouter
  copy:
    src: "{{ item }}"
    dest: "{{ kubelet_install_path }}/cert/kubelet/"
  with_items:
    - "{{ kubelet_certs_path }}/{{ inventory_hostname }}/cert.pem"
    - "{{ kubelet_certs_path }}/{{ inventory_hostname }}/key.pem"

- name: upload apiserver client certs 
  notify: restart kuberouter
  copy:
    src: "{{ item }}"
    dest: "{{ kubelet_install_path }}/cert/apiserver-client/"
  with_items:
    - "{{ apiserver_client_certs_kubelet }}/{{ inventory_hostname }}/cert.pem"
    - "{{ apiserver_client_certs_kubelet }}/{{ inventory_hostname }}/key.pem"

- name: upload scripts
  copy:
    src: "{{ item }}"
    dest: "{{ kubelet_install_path }}/"
    mode: u=rwx
  notify: restart kubelet
  with_items:
    - start.sh
    - stop.sh
