- name: ipset
  yum: 
    name: ipset
    state: present

- name: iptables
  yum: 
    name: iptables
    state: present

- name: iproute
  yum: 
    name: iproute
    state: present

- name: ipvsadm
  yum: 
    name: ipvsadm
    state: present

- name: supervisor
  yum: 
    name: supervisor
    state: present
